/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:145

DO $wrapper$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'geometry') THEN
    EXECUTE '
      CREATE OR REPLACE FUNCTION a5_point_to_cell_id(geom geometry, res int)
      RETURNS bigint
      LANGUAGE sql
      IMMUTABLE
      PARALLEL SAFE
      STRICT
      AS $f$
        SELECT a5_lonlat_to_cell_id(ST_X(geom), ST_Y(geom), res);
      $f$;
    ';
  END IF;
END;
$wrapper$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:171

CREATE OR REPLACE FUNCTION a5_lonlat_to_cell_id(lon numeric, lat numeric, res int)
RETURNS bigint
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
STRICT
AS $$
  SELECT a5_lonlat_to_cell_id(lon::double precision, lat::double precision, res);
$$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:40
-- a5pg::a5_cell_boundary_geojson
CREATE  FUNCTION "a5_cell_boundary_geojson"(
	"cell_hex" TEXT /* &str */
) RETURNS TEXT /* core::option::Option<alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_boundary_geojson_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:104
-- a5pg::a5_cell_children_ids
CREATE  FUNCTION "a5_cell_children_ids"(
	"cell_id" bigint, /* i64 */
	"target_resolution" INT /* i32 */
) RETURNS bigint[] /* alloc::vec::Vec<i64> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_children_ids_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:122
-- a5pg::a5_cell_id_boundary_geojson
CREATE  FUNCTION "a5_cell_id_boundary_geojson"(
	"cell_id" bigint /* i64 */
) RETURNS TEXT /* core::option::Option<alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_id_boundary_geojson_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:73
-- a5pg::a5_cell_id_to_lonlat_json
CREATE  FUNCTION "a5_cell_id_to_lonlat_json"(
	"cell_id" bigint /* i64 */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_id_to_lonlat_json_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:89
-- a5pg::a5_cell_parent_id
CREATE  FUNCTION "a5_cell_parent_id"(
	"cell_id" bigint, /* i64 */
	"target_resolution" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_parent_id_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:82
-- a5pg::a5_cell_resolution
CREATE  FUNCTION "a5_cell_resolution"(
	"cell_id" bigint /* i64 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_resolution_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:31
-- a5pg::a5_cell_to_lonlat_json
CREATE  FUNCTION "a5_cell_to_lonlat_json"(
	"cell_hex" TEXT /* &str */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_to_lonlat_json_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:21
-- a5pg::a5_lonlat_to_cell
CREATE  FUNCTION "a5_lonlat_to_cell"(
	"lon" double precision, /* f64 */
	"lat" double precision, /* f64 */
	"resolution" INT /* i32 */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_lonlat_to_cell_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:59
-- a5pg::a5_lonlat_to_cell_id
CREATE  FUNCTION "a5_lonlat_to_cell_id"(
	"lon" double precision, /* f64 */
	"lat" double precision, /* f64 */
	"resolution" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_lonlat_to_cell_id_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:15
-- a5pg::hello_a5pg
CREATE  FUNCTION "hello_a5pg"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'hello_a5pg_wrapper';
/* </end connected objects> */

