/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:118

DO $wrapper$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'geometry') THEN
    EXECUTE '
      CREATE OR REPLACE FUNCTION a5_point_to_cell(geom geometry, res int)
      RETURNS bigint
      LANGUAGE sql
      IMMUTABLE
      PARALLEL SAFE
      STRICT
      AS $f$
        SELECT a5_lonlat_to_cell(ST_X(geom), ST_Y(geom), res);
      $f$;
    ';
  END IF;
END;
$wrapper$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:144

CREATE OR REPLACE FUNCTION a5_lonlat_to_cell(lon numeric, lat numeric, res int)
RETURNS bigint
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
STRICT
AS $$
  SELECT a5_lonlat_to_cell(lon::double precision, lat::double precision, res);
$$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:54
-- a5pg::a5_cell_to_boundary
CREATE  FUNCTION "a5_cell_to_boundary"(
	"cell_id" bigint /* i64 */
) RETURNS double precision[][] /* core::option::Option<alloc::vec::Vec<alloc::vec::Vec<f64>>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_to_boundary_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:96
-- a5pg::a5_cell_to_children
CREATE  FUNCTION "a5_cell_to_children"(
	"cell_id" bigint, /* i64 */
	"target_resolution" INT /* i32 */
) RETURNS bigint[] /* alloc::vec::Vec<i64> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_to_children_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:39
-- a5pg::a5_cell_to_lonlat
CREATE  FUNCTION "a5_cell_to_lonlat"(
	"cell_id" bigint /* i64 */
) RETURNS double precision[] /* core::option::Option<alloc::vec::Vec<f64>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_to_lonlat_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:81
-- a5pg::a5_cell_to_parent
CREATE  FUNCTION "a5_cell_to_parent"(
	"cell_id" bigint, /* i64 */
	"target_resolution" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_cell_to_parent_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:74
-- a5pg::a5_get_resolution
CREATE  FUNCTION "a5_get_resolution"(
	"cell_id" bigint /* i64 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_get_resolution_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:22
-- a5pg::a5_lonlat_to_cell
CREATE  FUNCTION "a5_lonlat_to_cell"(
	"lon" double precision, /* f64 */
	"lat" double precision, /* f64 */
	"resolution" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5_lonlat_to_cell_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:13
-- a5pg::a5pg_info
CREATE  FUNCTION "a5pg_info"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5pg_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:7
-- a5pg::a5pg_version
CREATE  FUNCTION "a5pg_version"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a5pg_version_wrapper';
/* </end connected objects> */

